dist: trusty
sudo: false

language: python
cache: pip

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.6'
      env: TOXENV=metadata
    - python: '3.6'
      env: TOXENV=pep8
    - python: '3.6'
      env: TOXENV=docs

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov --env TOXENV
